import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "./components/Navbar.jsx";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className=" min-h-screen ">
          <Navbar />
          <div className="flex flex-col items-center justify-between p-24">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
